# Generated by Django 6.0.6 on 2026-06-13 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_date', models.DateField(db_index=True, unique=True)),
                ('spot_usd_per_oz', models.DecimalField(decimal_places=4, max_digits=14)),
                ('usd_to_egp', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fair_egp_gram_21k', models.DecimalField(decimal_places=4, help_text='Import-parity fair value.', max_digits=12)),
                ('actual_egp_gram_21k', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('premium_pct', models.DecimalField(blank=True, decimal_places=4, help_text='actual/fair - 1.', max_digits=8, null=True)),
                ('is_interpolated', models.BooleanField(default=False, help_text='True if any field was gap-filled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-obs_date',),
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(db_index=True)),
                ('usd_to_egp', models.DecimalField(decimal_places=4, help_text='EGP per 1 USD.', max_digits=10)),
                ('rate_type', models.CharField(choices=[('OFFICIAL', 'Official / CBE'), ('PARALLEL', 'Parallel / black market'), ('IMPLIED', 'Implied from XAU (EGP ÷ USD)')], default='OFFICIAL', max_length=10)),
                ('source', models.CharField(choices=[('GOLDAPI', 'GoldAPI.io (live tick)'), ('STOOQ', 'Stooq (free historical seed)'), ('YFINANCE', 'Yahoo Finance (free historical seed)'), ('COMPUTED', 'Computed / derived'), ('MANUAL', 'Manual entry'), ('GOLD_DIVISION', 'Egyptian Gold Division (retail)')], default='COMPUTED', max_length=20)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-rate_date', 'rate_type'),
                'constraints': [models.UniqueConstraint(fields=('rate_date', 'rate_type', 'source'), name='uniq_fxrate_day_type_source')],
            },
        ),
        migrations.CreateModel(
            name='GoldQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_date', models.DateField(db_index=True, help_text='Trading date the quote represents.')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EGP', 'Egyptian Pound')], max_length=3)),
                ('source', models.CharField(choices=[('GOLDAPI', 'GoldAPI.io (live tick)'), ('STOOQ', 'Stooq (free historical seed)'), ('YFINANCE', 'Yahoo Finance (free historical seed)'), ('COMPUTED', 'Computed / derived'), ('MANUAL', 'Manual entry'), ('GOLD_DIVISION', 'Egyptian Gold Division (retail)')], default='GOLDAPI', max_length=20)),
                ('price_per_oz', models.DecimalField(decimal_places=4, max_digits=14)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('prev_close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('change_abs', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('price_gram_24k', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_gram_22k', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_gram_21k', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_gram_18k', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('raw_payload', models.JSONField(blank=True, help_text='Full API response, kept so we never re-call.', null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When we hit the API (cache-TTL anchor).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-quote_date', 'currency'),
                'indexes': [models.Index(fields=['currency', '-quote_date'], name='prices_gold_currenc_c88808_idx')],
                'constraints': [models.UniqueConstraint(fields=('quote_date', 'currency', 'source'), name='uniq_goldquote_day_currency_source')],
            },
        ),
        migrations.CreateModel(
            name='LocalMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(db_index=True)),
                ('karat', models.IntegerField(choices=[(24, '24K (999)'), (22, '22K (916)'), (21, '21K (875) — Egyptian standard'), (18, '18K (750)')], default=21)),
                ('price_egp_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('GOLDAPI', 'GoldAPI.io (live tick)'), ('STOOQ', 'Stooq (free historical seed)'), ('YFINANCE', 'Yahoo Finance (free historical seed)'), ('COMPUTED', 'Computed / derived'), ('MANUAL', 'Manual entry'), ('GOLD_DIVISION', 'Egyptian Gold Division (retail)')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-price_date', 'karat'),
                'constraints': [models.UniqueConstraint(fields=('price_date', 'karat', 'source'), name='uniq_localprice_day_karat_source')],
            },
        ),
    ]
