# Generated by Django 6.0.6 on 2026-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(help_text='e.g. "XAU/EGP".', max_length=64)),
                ('status', models.CharField(help_text='"OK" or "ERROR".', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
